### PR TITLE
Added possibility to log requests in application that uses this library

### PR DESCRIPTION
**Pull request by aixkalur**
Sometimes it's needed to send request info to service provider to get info why some requests are failing. So i added simple closure to fill this role so it would be possible to gather requests data in main application.

### CODE REVIEW

**Comment by joosev** [comment]
This actually looks excellent.

**Comment by nicodemuz** [comment]
Consider using PSR-3 interface for logging:
https://www.php-fig.org/psr/psr-3/
https://github.com/php-fig/log

**Comment by aixkalur** [comment]
> Consider using PSR-3 interface for logging: https://www.php-fig.org/psr/psr-3/ https://github.com/php-fig/log

I actually considered it, but did not want to add required package without any discussion or not from repository owners, so i added simple feature without 3rd party dependency.  And this feature can easily be replaced by PSR-3 interface. Do i make the modifications?

**Comment by nicodemuz** [comment]
You could require the package using `^1|^2|^3` as the version, to avoid any compatibility issues for repositories using this library.

After this you can use dependency injection to inject [Psr\Log\LoggerInterface](https://github.com/php-fig/log/blob/master/src/LoggerInterface.php) in the Pakettikauppa API client.

This is pretty standard way of doing logging for many PHP libraries, see https://packagist.org/packages/psr/log/dependents?order_by=downloads

**Comment by joosev** [comment]
I will assign this for the developers to look into

**Pull request merged**
